# Usa a imagem oficial do Node.js na versão 20
FROM node:20

# Cria o diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Copia os arquivos de dependências primeiro (otimiza o tempo de build)
COPY package*.json ./

# Instala as dependências (ignorando as de desenvolvimento, como o Jest)
RUN npm install --omit=dev

# Copia o restante do código da aplicação
COPY . .

# Expõe a porta que o servidor usa
EXPOSE 3000

# Comando para iniciar o servidor
CMD ["npm", "start"]