name: Integracao Continua (CI)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  testes:
    runs-on: ubuntu-latest

    # Isso avisa o GitHub para criar um banco de dados temporário para o teste
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Baixar o codigo do repositorio
      uses: actions/checkout@v3

    - name: Configurar o Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Instalar dependencias
      run: npm install

    - name: Rodar os testes unitarios
      run: npm test